// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORMEFCoreDA.Models;

namespace myDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200125171809_AddingPhotoPropToEmployeeTable")]
    partial class AddingPhotoPropToEmployeeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ORMEFCoreDA.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhotoName");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 0,
                            Email = "EngAmmh86@gmail.com",
                            Name = "Ahmed"
                        },
                        new
                        {
                            Id = 2,
                            Department = 1,
                            Email = "EngMohammed@gmail.com",
                            Name = "Mohammed"
                        },
                        new
                        {
                            Id = 3,
                            Department = 0,
                            Email = "EngHesham@gmail.com",
                            Name = "Hesham"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
